### ISSUE TITLE
Ambiguous Documentation

### ISSUE THREAD

**Issue by herzi** [loopme/loopme-ios-sdk#3]
The page https://github.com/loopme/loopme-ios-sdk/wiki/iOS-9 lists things to do to work with iOS 9. Unfortunately the list does not specify if I have to do both of the things or if either of the things will be enough.

Also, does the demand side fully support HTTPS?

**Comment by bkorda** [comment]
Hi Herzi. Thank you for your questions. About iOS 9 - we've updated the documentation. Both things do the same. And about HTTPS. We are completely support HTTPS, but however some of the ads have http click links. In order to be compliant to them and still get paid for these conversions we kept HTTP the compatibility

**Comment by herzi** [comment]
So you basically say: „We're trying to use HTTPS only, but we still don't so you still have to disable ATS.“ Which I simply understand as „LoopMe is still not compatible with ATS“.

As Apple will restrict the use of ATS exceptions, what's your plan going forward until [January 2017](https://forums.developer.apple.com/thread/48979#146140)? I don't think I want to add an ad network to my app that is not even future-proof for the next four months.

**Comment by bkorda** [comment]
Actually we are saying that as a network we still let publishers get money for all ads that are incoming to the network. And it is up to publishers - enable HTTP and get the full monetization potential or refuse from implementing the instructions ( https://github.com/loopme/loopme-ios-sdk/wiki/iOS-9) loosing the part of benefits.

**Comment by herzi** [comment]
The point is: Starting with January 2017, Apple forces most of the App Developers to use ATS. Disabling ATS won't be an option anymore.

**Comment by bkorda** [comment]
Yes it is the whole Q4 of the New Year Eve and other big holidays for ads to catch up with. However if you do not plan to update your application before the restrictions applied then the better choice is to refuse from HTTP support from the beginning.
