### ISSUE TITLE
LoopMeSDK.framework

### ISSUE THREAD

**Issue by kokteyldev** [loopme/loopme-ios-sdk#4]
Is there a LoopMeSDK.framework file somewhere in your repository or did I misunderstand  "LoopMeSDK project changed to .framework template" statement in changelog?

**Comment by bkorda** [comment]
Hi, sorry for delay. 

You can use open source code or build framework file on your own with included project template.
Also I've added LoopMeSDK.framework to repo too. 

Best regards,
Bogdan
