### ISSUE TITLE
Version and Error public header files with CocoaPods

### ISSUE THREAD

**Issue by dwxw** [loopme/loopme-ios-sdk#5]
Hello, I'm integrating via CocoaPods and have hit a couple of issues it would be great if you could look at.  Would you be able to make the LoopMeDefinitions.h and LoopMeError.h files public?  XCode complains that it can't find them.  I'm after LoopMeDefinitions so I can access the sdk version, if you have another way of getting this that would also work.  I need LoopMeError so I can access the enum with the error definitions in it.  I think the problem is just that you've not made them publicly available in the Pod and through LoopMeSDK.h.  

Xcode won't find LoopMeDefinitions.h:
```
find . -name LoopMeDefinitions.h     
                                                                                
./Pods/Headers/Private/LoopMeSDK/LoopMeDefinitions.h
./Pods/LoopMeSDK/LoopMeSDK/Internal/Utility/LoopMeDefinitions.h
```

But happily finds LoopMeInterstitial.h:
```
find . -name LoopMeInterstitial.h           
                                                                         
./Pods/Headers/Private/LoopMeSDK/LoopMeInterstitial.h
./Pods/Headers/Public/LoopMeSDK/LoopMeInterstitial.h
./Pods/LoopMeSDK/LoopMeSDK/LoopMeInterstitial.h
```

Also be great if you could update the CocoaPods repo to the latest version, it's currently just 6.3.0.  Thanks in advance.  David.

**Comment by bkorda** [comment]
Hi David, thank you for your feedback.

I've included changes what you want in new CocoaPods version and already published it.

Best regards,
Bogdan
